---

- name: "Create directories"
  file:
    path: "{{ item }}"
    state: directory 
    owner: kevinp
    group: kevinp
    mode: 0755
  with_items:
    - "{{ PLEX_CONFIG }}"
    - "{{ PLEX_TVSERIES }}"
    - "{{ PLEX_MOVIES }}"

- name: "Create plex docker"
  command: "docker create --name=plex --userns=host --net=host --hostname=plex --domainname=thedarkarts.za.net -e VERSION=latest -e PUID=1000 -e PGID=1000 -e TZ=Africa/Johannesburg -v /config:{{ PLEX_CONFIG }} -v /data/tvseries:{{ PLEX_TVSERIES }} -v /data/movies:{{ PLEX_MOVIES }} linuxserver/plex"

- name: "Create plex.service service file"
  vars:
    DOCKER_DESC: "Plex Media Server"
    DOCKER_NAME: plex
  template:
    src: docker_template.service.j2
    dest: /usr/lib/systemd/system/plex.service

- name: "Start Plex docker"
  service:
    name: plex
    state: started
