---

# https://github.com/linuxserver/docker-mylar

- name: "Create directories"
  file:
    path: "{{ item }}"
    state: directory 
    owner: kevinp
    group: kevinp
    mode: 0755
  loop:
    - "{{ MYLAR_CONFIG }}"
    - "{{ MYLAR_DOWNLOADS }}"
    - "{{ MYLAR_COMICS }}"

- name: "Create mylar docker"
  vars:
    MYLAR_HOSTNAME: mylar
  command: "docker create --name={{ MYLAR_HOSTNAME }} --userns=host --net=host --hostname={{ MYLAR_HOSTNAME }} -e VERSION=latest -e PUID=1000 -e PGID=1000 -e TZ=Africa/Johannesburg -v {{ MYLAR_CONFIG }}:/config -v {{ MYLAR_DOWNLOADS }}:/downloads -v {{ MYLAR_COMICS }}:/comics linuxserver/mylar"

- name: "Create mylar.service service file"
  vars:
    DOCKER_DESC: "Mylar CBR Download Server"
    DOCKER_NAME: mylar
  template:
    src: docker_template.service.j2
    dest: /usr/lib/systemd/system/mylar.service

- name: "Start Mylar docker"
  systemd:
    name: mylar
    daemon_reload: yes
    enabled: yes
    state: started
