---

- name: "Create directories"
  file:
    path: "{{ item }}"
    state: directory 
    owner: kevinp
    group: kevinp
    mode: 0755
  with_items:
    - "{{ MYLAR_CONFIG }}"
    - "{{ MYLAR_DOWNLOADS }}"
    - "{{ MYLAR_COMICS }}"

- name: "Create mylar docker"
  vars:
    MYLAR_HOSTNAME: mylar01.example.com
  command: "docker create --name=mylar --userns=host --net=host --hostname={{ MYLAR_HOSTNAME }} -e VERSION=latest -e PUID=1000 -e PGID=1000 -e TZ=Africa/Johannesburg -v /config:{{ MYLAR_CONFIG }} -v /downloads:{{ MYLAR_DOWNLOADS }} -v /comics:{{ MYLAR_COMICS }} linuxserver/mylar"

- name: "Create mylar.service service file"
  vars:
    DOCKER_DESC: "Mylar CBR Download Server"
    DOCKER_NAME: mylar
  template:
    src: docker_template.service.j2
    dest: /usr/lib/systemd/system/mylar.service

- name: "Start Mylar docker"
  service:
    name: mylar
    state: started
