---

# https://hub.docker.com/r/linuxserver/sonarr/

- name: "Create directories"
  file:
    path: "{{ item }}"
    state: directory 
    owner: kevinp
    group: kevinp
    mode: 0755
  with_items:
    - "{{ SONARR_CONFIG }}"
    - "{{ SONARR_DOWNLOADS }}"

- name: "Create sonarr docker"
  vars:
    SONARR_HOSTNAME: sonarr
  command: "docker create --name={{ SONARR_HOSTNAME }} --userns=host --net=host --hostname={{ SONARR_HOSTNAME }} -p 8989:8989 -e VERSION=latest -e PUID=1000 -e PGID=1000 -e TZ=Africa/Johannesburg -v /etc/localtime:/etc/localtime:ro -v {{ SONARR_CONFIG }}:/config -v {{ SONARR_TVSERIES }}:/tvseries -v {{ SONARR_NFS_SRC_MEDIA03_4TB }}:/nfs_src_media03_4tb -v {{ SONARR_NFS_SRC_MEDIA04_4TB }}:/nfs_src_media04_4tb -v {{ SONARR_DOWNLOADS }}:/downloads -v /mnt/src_X_media02-4TB:/src_X_media02-4TB -v {{ SONARR_ANIMESERIES }}:/anime_series -v {{ NFS_SRC_MEDIA03_4TB_ROOT }}:/nfs_src_media03_4tb_root -v {{ NFS_SRC_MEDIA04_4TB_ROOT }}:/nfs_src_media04_4tb_root linuxserver/sonarr" 
    

- name: "Create sonarr.service service file"
  vars:
    DOCKER_DESC: "Sonarr Torrent Server"
    DOCKER_NAME: sonarr
  template:
    src: docker_template.service.j2
    dest: /usr/lib/systemd/system/sonarr.service

- name: "Start Sonarr docker"
  systemd:
    name: sonarr
    daemon_reload: yes
    enabled: yes
    state: started

