---

# https://github.com/jlesage/docker-jdownloader-2

- name: "Create directories"
  file:
    path: "{{ item }}"
    state: directory 
    owner: kevinp
    group: kevinp
    mode: 0755
  with_items:
    - "{{ JDOWNLOADER_CONFIG }}"
    - "{{ JDOWNLOADER_DOWNLOADS }}"

- name: "Create jdownloader-2 docker"
  vars:
    JDOWNLOADER_HOSTNAME: jdownloader01
  command: "docker create --name=jdownloader-2 --userns=host --net=host --hostname={{ JDOWNLOADER_HOSTNAME }} -e VERSION=latest -e PUID=1000 -e PGID=1000 -e TZ=Africa/Johannesburg -e KEEP_APP_RUNNING=1 -e VNC_PASSWORD=~jdo~Su5peR1a! -v {{ JDOWNLOADER_CONFIG }}:/config:rw -v {{ JDOWNLOADER_DOWNLOADS }}:/output:rw -p 5800:5800 jlesage/jdownloader-2"

- name: "Create jdownloader.service service file"
  vars:
    DOCKER_DESC: "JDownloader-2 Server"
    DOCKER_NAME: jdownloader-2
  template:
    src: docker_template.service.j2
    dest: /usr/lib/systemd/system/jdownloader-2.service

- name: "Start JDownloader-2 docker"
  service:
    name: jdownloader-2
    state: started
