---

# https://github.com/linuxserver/docker-sabnzbd

- name: "SABNZBD: Create directories"
  file:
    path: "{{ item }}"
    state: directory 
    owner: kevinp
    group: kevinp
    mode: 0755
  with_items:
    - "{{ SABNZBD_CONFIG }}"
    - "{{ SABNZBD_DOWNLOADS }}"
    - "{{ SABNZBD_INCOMPLETE_DOWNLOADS }}"

- name: "SABNZBD: Create docker"
  vars:
    SABNZBD_HOSTNAME: sabnzbd
  command: "docker create --name={{ SABNZBD_HOSTNAME }} --userns=host --net=host --hostname={{ SABNZBD_HOSTNAME }} -e VERSION=latest -e PUID=1000 -e PGID=1000 -e TZ=Africa/Johannesburg -v {{ SABNZBD_CONFIG }}:/config -v {{ SABNZBD_DOWNLOADS }}:/downloads -v {{ SABNZBD_INCOMPLETE_DOWNLOADS }}:/incomplete-downloads linuxserver/sabnzbd"

- name: "SABNZBD: Create sabnzbd.service service file"
  vars:
    DOCKER_DESC: "Sabnzbd Usenet Download Server"
    DOCKER_NAME: sabnzbd
  template:
    src: docker_template.service.j2
    dest: /usr/lib/systemd/system/sabnzbd.service

- name: "SABNZBD: Start docker"
  systemd:
    name: sabnzbd
    daemon_reload: yes
    enabled: yes
    state: started

- name: "SABNZBD: Wait for docker to start up"
  pause:
    seconds: 3

- name: "SABNZBD: Change host_whitelist entry in /config/sabnzbd.ini to allow for host checking for nginx web redirects"
  lineinfile:
    path: "{{ SABNZBD_CONFIG }}/sabnzbd.ini"
    regexp: '^host_whitelist ='
    line: 'host_whitelist = sabnzbd.{{ ansible_domain }},'
  ignore_errors: yes

