---
# tasks file for ansible-role-dlm-create-dockers

- name: "Restart docker"
  systemd:
    name: docker
    enabled: yes
    state: restarted

- name: Create base directories (/dockers/config and /dockers/downloads)
  file:
    name: "{{ item }}"
    state: directory
    mode: 0755
    owner: kevinp
    group: kevinp
  loop:
    - "{{ ROOTCFG }}"
    - "{{ ROOTDNLD }}"

- import_tasks: create_deluge.yml
  tags: create_deluge_docker
  ignore_errors: yes

- import_tasks: create_sonarr.yml
  tags: create_sonarr_docker
  ignore_errors: yes

- import_tasks: create_sabnzbd.yml
  tags: create_sabnzbd_docker
  ignore_errors: yes

- import_tasks: create_jdownloader-2.yml
  tags: create_jdownloader-2_docker
  ignore_errors: yes

- import_tasks: create_radarr.yml
  tags: create_radarr_docker
  ignore_errors: yes

