---
# tasks file for ansible-role-dlm-create-dockers

- include: create_plex.yml
  tags: create_plex_docker

- include: create_deluge.yml
  tags: create_deluge_docker

- include: create_sonarr.yml
  tags: create_sonarr_docker

- include: create_sabnzbd.yml
  tags: create_sabnzbd_docker

- include: create_mylar.yml
  tags: create_mylar_docker

- include: create_munin.yml
  tags: create_munin_docker

- include: create_jdownloader-2.yml
  tags: create_jdownloader-2_docker
